"""crear tablas iniciales

Revision ID: 6fecb555bfe0
Revises: 
Create Date: 2026-03-09 21:45:47.675679

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6fecb555bfe0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('estados_afiliado',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('descripcion', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('descripcion')
    )
    op.create_table('estados_civiles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('descripcion', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('descripcion')
    )
    op.create_table('generos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('descripcion', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('descripcion')
    )
    op.create_table('importaciones',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('fecha_importacion', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('cantidad_registros', sa.Integer(), nullable=False),
    sa.Column('cantidad_errores', sa.Integer(), nullable=False),
    sa.Column('estado', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('niveles_educativos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('descripcion', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('descripcion')
    )
    op.create_table('provincias',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('relaciones_dependencia',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('descripcion', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('descripcion')
    )
    op.create_table('errores_validacion',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('registro_origen', sa.String(length=500), nullable=False),
    sa.Column('campo', sa.String(length=100), nullable=False),
    sa.Column('descripcion_error', sa.String(length=500), nullable=False),
    sa.Column('fecha_error', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('id_importacion', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_importacion'], ['importaciones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('localidades',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('id_provincia', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_provincia'], ['provincias.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('domicilios',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('direccion', sa.String(length=255), nullable=True),
    sa.Column('codigo_postal', sa.String(length=20), nullable=True),
    sa.Column('id_localidad', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_localidad'], ['localidades.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('afiliados',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('apellido', sa.String(length=100), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('fecha_nacimiento', sa.Date(), nullable=False),
    sa.Column('dni', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('telefono', sa.String(length=50), nullable=True),
    sa.Column('numero_legajo', sa.String(length=50), nullable=False),
    sa.Column('fecha_ingreso', sa.Date(), nullable=True),
    sa.Column('fecha_alta', sa.Date(), nullable=True),
    sa.Column('titulo_obtenido', sa.String(length=255), nullable=True),
    sa.Column('marca_temporal_creacion', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('marca_temporal_actualizacion', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('id_genero', sa.Integer(), nullable=True),
    sa.Column('id_estado_civil', sa.Integer(), nullable=True),
    sa.Column('id_nivel_educativo', sa.Integer(), nullable=True),
    sa.Column('id_relacion_dependencia', sa.Integer(), nullable=True),
    sa.Column('id_estado_afiliado', sa.Integer(), nullable=False),
    sa.Column('id_domicilio', sa.Integer(), nullable=True),
    sa.Column('id_importacion', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_domicilio'], ['domicilios.id'], ),
    sa.ForeignKeyConstraint(['id_estado_afiliado'], ['estados_afiliado.id'], ),
    sa.ForeignKeyConstraint(['id_estado_civil'], ['estados_civiles.id'], ),
    sa.ForeignKeyConstraint(['id_genero'], ['generos.id'], ),
    sa.ForeignKeyConstraint(['id_importacion'], ['importaciones.id'], ),
    sa.ForeignKeyConstraint(['id_nivel_educativo'], ['niveles_educativos.id'], ),
    sa.ForeignKeyConstraint(['id_relacion_dependencia'], ['relaciones_dependencia.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dni'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('numero_legajo')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('afiliados')
    op.drop_table('domicilios')
    op.drop_table('localidades')
    op.drop_table('errores_validacion')
    op.drop_table('relaciones_dependencia')
    op.drop_table('provincias')
    op.drop_table('niveles_educativos')
    op.drop_table('importaciones')
    op.drop_table('generos')
    op.drop_table('estados_civiles')
    op.drop_table('estados_afiliado')
    # ### end Alembic commands ###
