"""descripcion

Revision ID: d674f37e1587
Revises: a1f2b3c4d5e6
Create Date: 2026-09-07 16:25:11.819744

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "d674f37e1587"
down_revision: str | Sequence[str] | None = "a1f2b3c4d5e6"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
